config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'teams#index'

  resources :call_types_and_campaigns, only: [:index]
  resources :industries, only: [:index]
  resources :discovery_questions, only: [:update]
  resources :product_task_details, only: [:update]
  resources :client_tasks, only: [:index, :update] do
    get 'questions', on: :member
    get 'states', on: :member
    get 'products', on: :member
  end
  resources :products, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/call_type.rb
class CallType < ApplicationRecord
end

app/models/campaign.rb
class Campaign < ApplicationRecord
end

app/models/client_benefit.rb
class ClientBenefit < ApplicationRecord
  belongs_to :product
  belongs_to :product_feature
end

app/models/client_task.rb
class ClientTask < ApplicationRecord
end

app/models/client_type.rb
class ClientType < ApplicationRecord
end

app/models/discovery_question.rb
class DiscoveryQuestion < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_feature_descriptions
  has_many :product_feature, through: :product_feature_descriptions
end

app/models/product_feature.rb
class ProductFeature < ApplicationRecord
  has_many :product_feature_descriptions
  has_many :products, through: :product_feature_descriptions
  has_one :client_task
end

app/models/product_feature_description.rb
class ProductFeatureDescription < ApplicationRecord
  belongs_to :product
  belongs_to :product_feature
end

app/models/product_task_detail.rb
class ProductTaskDetail < ApplicationRecord
  belongs_to :product
  belongs_to :client_task
end

app/models/team.rb
class Team < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  enum role: [ :admin, :user ]

  validates :role, presence: true

  def is_admin?
    self.role == 'admin'
  end

  def is_user?
    self.role == 'user'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  private

  def render_unauthorized
    render json: { error: 'unauthorized' }, status: :unauthorized
  end
end

app/controllers/client_tasks_controller.rb
class ClientTasksController < ApplicationController
  def index
    @client_tasks = ClientTask.all.order(:name)
    @discovery_questions = DiscoveryQuestion.all.order(:id)
  end

  def questions
    keys = params[:id].split(',')
    @client_tasks = ClientTask.where(key: keys).order(:id)
  end

  # TODO; eh this should be renamed
  def states
    keys = params[:id].split(',')
    @products = Product.all
    product_task_details = ProductTaskDetail.joins(:product, :client_task).where('client_tasks.key IN (?)', keys).order(:id)
    @client_tasks = product_task_details.group_by(&:client_task)
  end

  def update
    if current_user.is_admin?
      client_task = ClientTask.find(params[:id])
      client_task.questions = client_task_param[:questions] if client_task_param[:questions]
      client_task.info = client_task_param[:info] if client_task_param[:info]
      client_task.save

      render json: client_task.to_json
    else
      render_unauthorized
    end
  end

  private
  def client_task_param
    @client_task_param ||= params[:client_tasks] || {}
  end
end

app/controllers/discovery_questions_controller.rb
class DiscoveryQuestionsController < ApplicationController
  def update
    if current_user.is_admin?
      discovery_question = DiscoveryQuestion.find(params[:id])
      discovery_question.questions = params[:discovery_questions][:questions]
      discovery_question.save

      render json: discovery_question.to_json
    else
      render_unauthorized
    end
  end
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
  def index
    @client_types = ClientType.all
  end
end

app/controllers/product_task_details_controller.rb
class ProductTaskDetailsController < ApplicationController
  def update
    if current_user.is_admin?
      product_task_detail = ProductTaskDetail.find(params[:id])
      product_task_detail.current_state = product_task_details_param[:current_state] if product_task_details_param[:current_state]
      product_task_detail.future_state = product_task_details_param[:future_state] if product_task_details_param[:future_state]
      product_task_detail.insights = product_task_details_param[:insights] if product_task_details_param[:insights]
      product_task_detail.benefits = product_task_details_param[:benefits] if product_task_details_param[:benefits]
      product_task_detail.features = product_task_details_param[:features] if product_task_details_param[:features]
      product_task_detail.save

      render json: product_task_detail.to_json
    else
      render_unauthorized
    end
  end

  private

  def product_task_details_param
    product_task_details_param ||= params[:product_task_details]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.where('lower(name) = ?', params['id']).first
    @product_task_details = ProductTaskDetail.where('product_id = ? AND client_task_id in (?)', @product.id, client_tasks.map(&:id))
  end

  private

  def client_task_keys
    @client_task_keys ||= params[:client_tasks].split(',')
  end

  def client_tasks
    @client_tasks ||= ClientTask.where(key: client_task_keys).order(:id)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_flash.erb
<% if notice || alert %>
<div class="flash <%= 'flash--notice' if flash.notice.present? %> <%= 'flash--alert' if flash.alert.present? %>">
  <% if notice %>
    <div class="container flash__message"><%= notice %></div>
  <% end %>
  <% if alert %>
    <div class="container flash__message"><%= alert %></div>
  <% end %>
  </div>
</div>
<% end %>

app/views/application/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="page-controls">
      <% if prev_page_link.present? %>
        <%= link_to 'BACK', prev_page_link, class: 'btn btn--secondary prev' %>
      <% end %>

      <% if next_page_link.present? %>
        <% if next_page_link == root_path %>
          <%= link_to 'FINISH', next_page_link, class: 'btn next', 'data-reset-link': '' %>
        <% else %>
          <%= link_to 'NEXT', next_page_link, class: 'btn next' %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/application/_header.html.erb
<header class="header">
  <div class="header__gradient"></div>

  <div class="container">
    <% if user_signed_in? %>
    <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "header__logout") %>
    <% end %>

    <%= link_to root_path, class: 'header__link', 'data-reset-link': '' do %>
      <div class="header__title">
        <svg id="myob-logo" class="header__logo" data-name="myob-logo" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 283.5 116.4" aria-label="MYOB Home" data-component-info="{&quot;logoAltText&quot;:&quot;MYOB Home&quot;,&quot;logoUrl&quot;:&quot;https://www.myob.com/au&quot;}">
          <title>MYOB Home</title>
          <defs>
            <linearGradient id="myob-logo-gradient" gradientUnits="userSpaceOnUse" x1="0" y1="58.2083" x2="283.4646" y2="58.2083">
              <stop offset="0.36" stop-color="#6100A5"></stop>
              <stop offset="0.4557" stop-color="#7001A0"></stop>
              <stop offset="0.6409" stop-color="#980293"></stop>
              <stop offset="0.8947" stop-color="#D9057E"></stop>
              <stop offset="0.97" stop-color="#ED0677"></stop>
            </linearGradient>
          </defs>
          <g fill="url(#myob-logo-gradient)">
            <path d="M46.8,34.2 c-4.4-5.3-11.1-8.6-19.4-8.6C10.8,25.5,0,37.3,0,52.7V88h5.1c3.5-0.2,10.3-1.9,10.5-12V52.4c0-6.9,4.8-11.6,11.8-11.6 c10.3,0,11.4,8.2,11.4,11.6V88h5.1c3.4-0.2,10.2-1.9,10.5-11.9V52.4c0-6.9,5-11.6,11.8-11.6c10.3,0,11.5,8.2,11.5,11.6V88h5.1 c3.5-0.2,10.4-1.9,10.5-12.2V52.7c0-16-10.1-27.2-27.1-27.2C58.3,25.5,51.4,28.9,46.8,34.2"></path>
            <path d="M138.3,33.8l-13.1,36.4l-14.3-37.7c-2.2-6-7.8-5.6-7.8-5.6H90.9l24.2,59.2c0-0.1,0-0.1-0.1-0.2 c0,0,0,0.1,0.1,0.2c0,0.1,0.1,0.2,0.1,0.2l-0.1-0.3c0.8,2.4,0.6,3.7-0.2,6.1l-0.5,1.5c-2.8,7-6.8,8.9-15.2,8.4v0.1l5.8,14.3 c10.8-0.2,19-3.8,24.4-17.3l29.1-72.2l0,0l-10.9,0c0,0,0,0,0,0C147.1,26.9,140.9,27.1,138.3,33.8"></path>
            <path d="M170.1,57.7 c0-10.5,6.7-17.9,15-17.9c8.3,0,15,7.3,15,17.9c0,10.3-6.7,17.4-15,17.4C176.8,75.1,170.1,68,170.1,57.7 M154.5,57.6 c0,18.2,13.7,31.8,30.6,31.8c16.9,0,30.7-13.6,30.7-31.8c0-18.2-13.8-32-30.7-32C168.2,25.5,154.5,39.4,154.5,57.6"></path>
            <path d="M236.6,57.7c0-9.7,7-17.5,15.6-17.5 c8.6,0,15.6,7.6,15.6,17.5c0,9.7-7,17.1-15.6,17.1C243.6,74.9,236.6,67.2,236.6,57.7 M233.4,0L233.4,0 c-10.6,0-12.3,7.2-12.5,10.6V88l7.5,0c6,0.1,7.4-3.7,7.5-5.9v-0.3v-0.3c4.7,5,11.2,7.8,18.6,7.8c16,0,29-13.7,29-31.7 c0-18.1-13-31.8-29-31.8c-7,0-13.2,2.6-17.9,7.1V0H233.4z"></path>
          </g>
        </svg>
        <div class="header__text">Mission Guidebook<%= " > #{content_for(:title)}" if content_for?(:title) %></div>
      </div>
    <% end %>
  </div>
</header>

app/views/client_tasks/index.html.erb
<% title 'Mission Active' %>

<main>
  <div class="container">
    <div class="row">
      <div class="col-xs-9">
        <p>Learn about your client and determine discussion target points <strong>(limit of 3):</strong></p>

        <div class="row" data-container="client-task">
          <% @client_tasks.each do |client_task| %>
          <div class="col-xs-4">
            <button data-client-task="<%= client_task.key %>" class="card card--wide btn-toggle"><%= client_task.name %></button>
          </div>
          <% end %>
        </div>

        <p>Mission Brief guidelines:</p>

        <div class="row">
          <% @discovery_questions.each do |discovery_question| %>
          <div class="col-xs-4">
            <%= render partial: 'shared/editable_textarea', locals: { key: 'discovery-questions', resource: discovery_question, attr: 'questions', data: discovery_question.questions }%>
          </div>
          <% end %>
        </div>
      </div>

      <div class="col-xs-3 sidebar">
        <%= render partial: 'shared/client_info' %>
      </div>
    </div>
  </div>
</main>

<%= render partial: "footer", locals: { prev_page_link: industries_path, next_page_link: client_tasks_path } %>

app/views/client_tasks/products.html.erb
<main>
  <div class="container">
    <p class="page-instruction">Choose your product thats features best match the client needs</p>

    <div class="tab-group">
    <% @products.each do |product| %>
      <button data-id="<%= product.id %>" data-product="<%= product.name.downcase %>" class="tab__item btn-toggle btn-product"><%= product.name %></button>
    <% end %>
    </div>

    <div class="row">
      <div class="col-xs-9">
        <br>
        <p>QUESTIONS</p>
        <div class="row">
          <% @client_tasks.each do |client_task| %>
          <div class="col-xs-4">
            <%= render partial: 'shared/editable_textarea', locals: { key: 'client-tasks', attr: 'features', resource: client_task, data: client_task.features }%>
          </div>
          <% end %>
        </div>
      </div>

      <div class="col-xs-3 sidebar">
        <%= render 'shared/client_info' %>
      </div>
    </div>
  </div>
</main>

<%= render partial: "footer", locals: { prev_page_link: client_tasks_path, next_page_link: products_path } %>

app/views/client_tasks/questions.html.erb
<main>
  <div class="container">
    <p class="page-instruction">Focus on the task and find a need that MYOB can help them with:</p>

    <div class="row">
      <div class="col-xs-9">
        <br>
        <p>QUESTIONS</p>
        <div class="row">
          <% @client_tasks.each do |client_task| %>
          <div class="col-xs-4">
            <%= render partial: 'shared/editable_textarea', locals: { key: 'client-tasks', attr: 'questions', resource: client_task, data: client_task.questions }%>
          </div>
          <% end %>
        </div>

        <br>
        <p>INFO</p>
        <div class="row">
          <% @client_tasks.each do |client_task| %>
          <div class="col-xs-4">
            <%= render partial: 'shared/editable_textarea', locals: { key: 'client-tasks', attr: 'info', resource: client_task, data: client_task.info }%>
          </div>
          <% end %>
        </div>
      </div>

      <div class="col-xs-3 sidebar">
        <%= render 'shared/client_info' %>
      </div>
    </div>
  </div>
</main>

<%= render partial: "footer", locals: { prev_page_link: client_tasks_path, next_page_link: client_tasks_path } %>

app/views/client_tasks/states.html.erb
<main>
  <div class="container">
    <p class="page-instruction">Assess the current and future state of their topics:</p>

    <div class="tab-group">
    <% @products.each do |product| %>
      <button data-id="<%= product.id %>" data-product="<%= product.name.downcase %>" class="tab__item btn-toggle btn-product"><%= product.name %></button>
    <% end %>
    </div>

    <% @client_tasks.each do |client_task, product_task_details| %>
    <br>
    <p><%= client_task.name %></p>

    <% product_task_details.each do |product_task_detail| %>
    <div class="row product-row product-row--<%= product_task_detail.product.name.downcase %>">
      <div class="col-xs-2">
        <small><%= product_task_detail.product.name.downcase %></small>
        <%= render partial: 'shared/editable_textarea', locals: { name: 'Current State', key: 'product-task-details', attr: 'current_state', resource: product_task_detail, data: product_task_detail.current_state }%>
      </div>

      <div class="col-xs-2">
        <small><%= product_task_detail.product.name.downcase %></small>
        <%= render partial: 'shared/editable_textarea', locals: { name: 'Future State', key: 'product-task-details', attr: 'future_state', resource: product_task_detail, data: product_task_detail.future_state }%>
      </div>

      <div class="col-xs-2">
        <small><%= product_task_detail.product.name.downcase %></small>
        <%= render partial: 'shared/editable_textarea', locals: { name: 'Insights', key: 'product-task-details', attr: 'insights', resource: product_task_detail, data: product_task_detail.insights }%>
      </div>

      <div class="col-xs-2">
        <small><%= product_task_detail.product.name.downcase %></small>
        <%= render partial: 'shared/editable_textarea', locals: { name: 'Features', key: 'product-task-details', attr: 'features', resource: product_task_detail, data: product_task_detail.features }%>
      </div>

      <div class="col-xs-2">
        <small><%= product_task_detail.product.name.downcase %></small>
        <%= render partial: 'shared/editable_textarea', locals: { name: 'Benefits', key: 'product-task-details', attr: 'benefits', resource: product_task_detail, data: product_task_detail.benefits }%>
      </div>
    </div>
    <% end %>
  <% end %>
  </div>
</main>

<%= render partial: "footer", locals: { prev_page_link: client_tasks_path, next_page_link: products_path } %>

app/views/products/_accountedge.html.erb
<div class="row">
  <div class="col-xs-4">
    <div class="product product--accountedge">
      <div class="product__recommend">BEST CHOICE FOR MOST BUSINESSES</div>

      <div class="product__head">
        <div class="product__name">ACCOUNTEDGE BASIC</div>

        <div class="product__price">
          <sup class="product__dollar">$</sup>549
        </div>

        <div class="product__description">Mac software to manage your basic accounting needs</div>
      </div>

      <div class="product__body">
        <ul>
          <li>Issue quotes and invoices</li>
          <li>Instant GST &amp; BAS reports</li>
          <li>Simplify GST calculations</li>
          <li>Track payments</li>
          <li>Full general ledger</li>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-xs-4">
    <div class="product product--accountedge product--recommended">
      <div class="product__recommend">BEST CHOICE FOR MOST BUSINESSES</div>

      <div class="product__head">
        <div class="product__name">ACCOUNTEDGE PRO</div>

        <div class="product__price">
          <sup class="product__dollar">$</sup>1,699
        </div>

        <div class="product__description">Accounting, inventory and payroll on a Mac</div>
      </div>

      <div class="product__body">
        <ul>
          <li>Issue quotes and invoices</li>
          <li>Instant PAYG, GST &amp; BAS reports</li>
          <li>Simplify GST calculations</li>
          <li>Track payments</li>
          <li>Full general ledger</li>
          <li>Job costing and tracking</li>
          <li>Run business on the go</li>
          <li>Powerful stock management</li>
          <li>No hassles in calculating commissions</li>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-xs-4">
    <div class="product product--accountedge">
      <div class="product__recommend">BEST CHOICE FOR MOST BUSINESSES</div>

      <div class="product__head">
        <div class="product__name">ACCOUNTEDGE NETWORK</div>

        <div class="product__price">
          <sup class="product__dollar">$</sup>3,599
        </div>

        <div class="product__description">Multi-user accounting, inventory &amp; payroll on a Mac</div>
      </div>

      <div class="product__body">
        <ul>
          <li>Issue quotes and invoices</li>
          <li>Instant GST &amp; BAS reports</li>
          <li>Simplify GST calculations</li>
          <li>Track payments</li>
          <li>Full general ledger</li>
          <li>Job costing and tracking</li>
          <li>Run business on the go</li>
          <li>Powerful stock management</li>
          <li>No hassles in calculating commissions</li>
          <li>Multi-currency support</li>
          <li>Multi-user support</li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/products/_accountright.html.erb
<div class="row">
  <div class="col-xs-4">
    <div class="product product--accountright">
      <div class="product__recommend">BEST CHOICE FOR MOST BUSINESSES</div>

      <div class="product__head">
        <div class="product__name">ACCOUNTRIGHT STANDARD</div>

        <div class="product__price">
          <sup class="product__dollar">$</sup>61<sub class="product__permonth">/month</sub>
        </div>

        <div class="product__description">For businesses that need to manage inventory</div>
      </div>

      <div class="product__body">
        <ul>
          <li>Calculate &amp; track GST</li>
          <li>Manage bills, quotes, invoices &amp; expenses</li>
          <li>Create purchase &amp; manage suppliers</li>
          <li>Track jobs &amp; manage inventory</li>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-xs-4">
    <div class="product product--accountright product--recommended">
      <div class="product__recommend">BEST CHOICE FOR MOST BUSINESSES</div>

      <div class="product__head">
        <div class="product__name">ACCOUNTRIGHT PLUS</div>

        <div class="product__price">
          <sup class="product__dollar">$</sup>92<sub class="product__permonth">/month</sub>
        </div>

        <div class="product__description">For businesses that need to manage inventory and payroll</div>
      </div>

      <div class="product__body">
        <ul>
          <li>Calculate &amp; track GST</li>
          <li>Manage bills, quotes, invoices &amp; expenses</li>
          <li>Create purchase &amp; manage suppliers</li>
          <li>Track jobs &amp; manage inventory</li>
          <li>Bill by time</li>
          <li>Pay employees, pay super &amp; track leave</li>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-xs-4">
    <div class="product product--accountright">
      <div class="product__recommend">BEST CHOICE FOR MOST BUSINESSES</div>

      <div class="product__head">
        <div class="product__name">ACCOUNTRIGHT PREMIER</div>

        <div class="product__price">
          <sup class="product__dollar">$</sup>121<sub class="product__permonth">/month</sub>
        </div>

        <div class="product__description">For businesses that manage multiple company accounts</div>
      </div>

      <div class="product__body">
        <ul>
          <li>Calculate &amp; track GST</li>
          <li>Manage bills, quotes, invoices &amp; expenses</li>
          <li>Create purchase &amp; manage suppliers</li>
          <li>Track jobs &amp; manage inventory</li>
          <li>Bill by time</li>
          <li>Pay employees, pay super &amp; track leave</li>
          <li>Manage 2 company accounts</li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/products/_essentials.html.erb
<div class="row">
  <div class="col-xs-4">
    <div class="product product--essentials">
      <div class="product__recommend">BEST CHOICE FOR MOST BUSINESSES</div>

      <div class="product__head">
        <div class="product__name">STARTER</div>

        <div class="product__price">
          <sup class="product__dollar">$</sup>25<sub class="product__permonth">/month</sub>
        </div>

        <div class="product__description">Perfect for those just starting up</div>
      </div>

      <div class="product__body">
        <ul>
          <li>Great for people new to accounting</li>
          <li>Keep on top of GST &amp; BAS</li>
          <li>Works on both MAC &amp; PC</li>
          <li>Always up-to-date, and securely backed up online</li>
          <li>Payroll for one</li>
          <li>MYOB BankFeeds* (25 transactions p/m)</li>
          <li>Create five invoices p/m</li>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-xs-4">
    <div class="product product--essentials product--recommended">
      <div class="product__recommend">BEST CHOICE FOR MOST BUSINESSES</div>

      <div class="product__head">
        <div class="product__name">PAYROLL FOR ONE</div>

        <div class="product__price">
          <sup class="product__dollar">$</sup>40<sub class="product__permonth">/month</sub>
        </div>

        <div class="product__description">Great for small businesses and sole traders</div>
      </div>

      <div class="product__body">
        <ul>
          <li>Great for people new to accounting</li>
          <li>Keep on top of GST &amp; BAS</li>
          <li>Works on both MAC &amp; PC</li>
          <li>Always up-to-date, and securely backed up online</li>
          <li>Payroll for one</li>
          <li>MYOB BankFeeds*</li>
          <li>Unlimited invoices</li>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-xs-4">
    <div class="product product--essentials">
      <div class="product__recommend">BEST CHOICE FOR MOST BUSINESSES</div>

      <div class="product__head">
        <div class="product__name">UNLIMITED PAYROLL</div>

        <div class="product__price">
          <sup class="product__dollar">$</sup>50<sub class="product__permonth">/month</sub>
        </div>

        <div class="product__description">For those taking care of business, and payroll</div>
      </div>

      <div class="product__body">
        <ul>
          <li>Great for people new to accounting</li>
          <li>Keep on top of GST &amp; BAS</li>
          <li>Works on both MAC &amp; PC</li>
          <li>Always up-to-date, and securely backed up online</li>
          <li>Unlimited Payroll</li>
          <li>MYOB BankFeeds*</li>
          <li>Unlimited invoices</li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<main>
  <div class="container">
    <h1>PRODUCTS</h1>

    <p>Product table will go here</p>
  </div>
</main>

<%= render partial: "footer", locals: { prev_page_link: topics_path, next_page_link: nil } %>

app/views/products/show.html.erb
<main>
  <div class="container">
    <p class="page-title">MYOB <%= @product.name %></p>

    <% @product_task_details.each do |product_task_detail| %>
      <p>Client Task: <%= product_task_detail.client_task.name %></p>
      <p>Features: <%= product_task_detail.features %></p>
      <hr>
    <% end %>

    <%= render @product.name.downcase %>
  </div>
</main>

<%= render partial: "footer", locals: { prev_page_link: client_tasks_path, next_page_link: root_path } %>